server:
  port: 4666
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./test.db
#    password: dbuserpass
#    username: dbuser
#    name: dbname
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate